name: "Checkout Code & Submodule"
description: "Checkout Code and run command to initialize submodule"
runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Submodule
      run: |
        git submodule init
        git submodule update
      shell: bash