name: Android Publish

on: [ workflow_dispatch ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      KEY_PROD: ${{ secrets.KEY_PROD }}
      KEY_ALIAS_ALLSET: ${{ secrets.KEY_ALIAS_ALLSET }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure Step
        uses: ./.github/workflows/actions/configure

      - name: SetLocalProperties
        run: |
          echo KEY_PROD=$KEY_PROD >> local.properties

      - name: Signing App Release
        run: |
          ./gradlew app:bundleRelease
          ./gradlew app:assembleRelease

      - name: Obtain Package Name
        run: |
          currentPackage=`grep applicationId ./buildSrc/src/main/kotlin/ConfigureApp.kt | awk -F" " '{ print $5 }' `
          packageFormatted=`echo $currentPackage | sed 's/.\(.*\)/\1/' | sed 's/\(.*\)./\1/'`
          echo "Package: $packageFormatted"

      - name: Deploy to Alpha
        run: |
          echo "Package: $packageFormatted"
          echo $packageFormatted
