name: Android Publish
run-name: Android Publish execute by @${{ github.actor }}

on: [ workflow_dispatch ]

env:
  PACKAGE: ${{ secrets.PACKAGE }}
  KEY_PROD: ${{ secrets.KEY_PROD }}
  SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
  SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
  SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
          check-latest: true

      - name: Setup Project
        uses: ./.github/actions/android

      - name: SetLocalProperties
        run: |
          echo KEY_PROD=$KEY_PROD >> local.properties

      - name: Signing App Release
        run: |
          ./gradlew app:bundleRelease

      - name: Obtain Package Name
        run: |
          currentPackage=`grep applicationId ./buildSrc/src/main/kotlin/ConfigureApp.kt | awk -F" " '{ print $5 }' `
          packageFormatted=`echo $currentPackage | sed 's/.\(.*\)/\1/' | sed 's/\(.*\)./\1/'`
          echo "CurrentPackage: $currentPackage"
          echo "PackageFormatted: $packageFormatted"
          echo $packageFormatted
          echo "PACKAGE=$packageFormatted" >> $GITHUB_ENV

      - name: Deploy to Alpha
        uses: r0adkll/upload-google-play@v1.0.17
        with:
          serviceAccountJsonPlainText: ${{ secrets.SIGNING_SERVICE_ACCOUNT }}
          packageName: com.hacybeyker.allset
          releaseFiles: ./app/build/outputs/bundle/release/app-release.aab
          track: beta