name: Android Publish

on: [ workflow_dispatch ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      KEY_PROD: ${{ secrets.KEY_PROD }}
      KEY_ALIAS_ALLSET: ${{ secrets.KEY_ALIAS_ALLSET }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Config Step
        uses: ./.github/workflows/actions/config-step

      - name: SetLocalProperties
        run: |
          echo KEY_PROD=$KEY_PROD >> local.properties

      - name: Signing App Release
        run: |
          ./gradlew app:bundleRelease
          ./gradlew app:assembleRelease

      - name: Upload Artifact APK Release
        uses: actions/upload-artifact@v2
        with:
          name: apk-release
          path: ./app/build/outputs/apk/release
